---
title: "mutant_standards_verification"
author: "Haider Inam"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../.."))
# rm(list=ls())

library(stringr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tictoc)
library(doParallel)
library(foreach)
library(RColorBrewer)
library(ggpubr)
library(pROC)
library(reshape2)
library(dr4pl)
library(tidyr)
library(scales)

cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        # axis.line = element_line(color = "black"),
        axis.text = element_text(face="bold",color="black",size="11"),
        text=element_text(size=11,face="bold"),
        axis.title=element_text(face="bold",size="11"))

```


### Downloading mutant standards data (single mutant IC50s)
```{r}
# net_gr_wodrug=0.055
# conc_for_predictions=0.8

ic50data_all <- read.csv("Figures/Figure_3C/inputs/IC50HeatMap_v2.csv", header = TRUE, stringsAsFactors = FALSE)


# Convert to long format
ic50data_long <- ic50data_all %>%
  pivot_longer(
    cols = -c(species, replicate),  # all columns except 'species' and 'replicate'
    names_to = "dose",
    values_to = "rel.viab"
  ) %>%
  mutate(dose = round(as.numeric(gsub("X","",dose)),4))  # convert dose to numeric for proper ordering/plotting



# Removing species that are not present in the DMS dataset
ic50data_long=ic50data_long%>%filter(!species%in%c("E355G",
                                                   "E355A",
                                                   "F359V",
                                                   "F359L",
                                                   "M244V",
                                                   "WT"))

# The code below can be used to download the mean IC50 data for all mutants (i.e. no replicate-level data)
# ic50data_all=read.csv("data/ic50data/IC50HeatMap.csv",header = T,stringsAsFactors = F)
# # ic50data_all=read.csv("../data/IC50HeatMap.csv",header = T,stringsAsFactors = F)
# 
# ic50data_all=ic50data_all%>%filter(species%in%c("WT","V299L_H","E355A","D276G_maxi","H396R","F317L","F359I","E459K","G250E","F359C","F359V","M351T","L248V","E355G_maxi","Q252H_maxi","Y253F","F486S_maxi","H396P_maxi","E255K","Y253H","T315I","E255V"))
# 
# 
# ic50data_all=ic50data_all%>%
#   mutate(species=case_when(species=="F486S_maxi"~"F486S",
#                           species=="H396P_maxi"~"H396P",
#                           species=="Q252H_maxi"~"Q252H",
#                           species=="E355G_maxi"~"E355G",
#                           species=="D276G_maxi"~"D276G",
#                           species=="V299L_H" ~ "V299L",
#                           TRUE ~as.character(species)))
# 
# ic50data_long=read.csv("data/ic50data/ic50data_all_conc.csv",header = T,stringsAsFactors = F)
# # ic50data_long=read.csv("../output/ic50data_all_conc.csv",header = T,stringsAsFactors = F)
# ic50data_long$netgr_pred=net_gr_wodrug-ic50data_long$drug_effect
```


### Downloading mutant standards data (Pooled mutant DMS data)
```{r}
# ic50data_long=ic50data_long%>%mutate(species=mutant,rel.viab=y_model,dose=conc)

data_dms=read.csv("Figures/Figure_3C/inputs/all_corrected_without_poorly_fit_removed_w_drc_11.csv",header = T,stringsAsFactors = F)
data_dms=data_dms%>%filter(species%in%unique(ic50data_long$species))


data_dms_subset=data_dms[,c(1:21)]
# data_dms_subset=data_dms_subset%>%mutate(rel.viab=exp(netgr_corr_rep1.low*144)/exp(0.055*144),
#                                          alpha=-log(rel.viab)/144)

data_dms_subset=data_dms_subset%>%dplyr::select(-c("dose.low","dose.medium","dose.high"))

data_dms_subset <- data_dms_subset %>%
  rename(netgr_corr_rep1.il3 = netgr_obs_rep1.il3,
         netgr_corr_rep2.il3 = netgr_obs_rep2.il3)

# data_dms_subset
data_dms_subset <- data_dms_subset %>%
  pivot_longer(
    cols = starts_with("netgr_corr"),
    names_to = c("replicate", "dose"),
    names_pattern = "netgr_corr_(rep\\d+)\\.(\\w+)",
    values_to = "netgr"
  )

data_dms_subset=data_dms_subset%>%mutate(Dose=case_when(dose%in%"low"~0.3,
                                                        dose%in%"il3"~0,
                                                        dose%in%"medium"~0.6,
                                                        dose%in%"high"~1.2))

data_dms_subset=data_dms_subset%>%mutate(rel.viab=exp(netgr*72)/exp(0.055*72),
                                         alpha=-log(rel.viab)/72)

data_dms_subset=data_dms_subset%>%filter(!Dose%in%0)

# data_dms_subset_filtered=data_dms_subset%>%filter(species%in%unique(data_sum_model$species))
data_dms_subset_filtered=data_dms_subset%>%filter(species%in%unique(ic50data_long$species))
```


### Plotting mutant standards data
```{r}

# ic50data_long=ic50data_long%>%filter(dose<=5,dose>0.04)
# Order species by resistance (descending relative viability at 1.250 uM)
ordered_species <- ic50data_long %>%
  # filter(!species%in%c("F359C","F359I")) %>%
  filter(dose == 1.25,replicate==1) %>%
  arrange(desc(rel.viab)) %>%
  pull(species) %>%
  as.character()

# Apply ordered levels to both datasets
# ic50data_long=ic50data_long%>%filter(!species%in%c("F359C","F359I"))
ic50data_long$species <- factor(ic50data_long$species, levels = ordered_species)

# data_dms_subset_filtered=data_dms_subset_filtered%>%filter(!species%in%c("F359C","F359I"))
data_dms_subset_filtered$species <- factor(data_dms_subset_filtered$species, levels = ordered_species)

label_positions <- ic50data_long %>%
  # filter(!species%in%c("F359C","F359I")) %>%
  group_by(species) %>%
  summarise(
    x = .010,             # consistent left edge on log10 scale
    y = 0.15,           # high enough for all panels
    label = unique(species)
  )


getPalette = colorRampPalette(brewer.pal(11, "Spectral"))
color_values <- getPalette(length(ordered_species))
names(color_values) <- ordered_species  # ensures proper mapping

# a=ic50data_long
# a$dose=round(a$dose,2)
ggplot(ic50data_long,
       aes(x=dose,y=rel.viab))+
  geom_point(size=1,aes(color=species))+
  geom_line(aes(group = interaction(species, replicate)),
            linetype="dashed",
            color="gray")+
  geom_point(data=data_dms_subset_filtered,size=2.5,color="black",shape=24,aes(x=Dose,y=rel.viab,fill=species))+
  facet_wrap(~species,
             nrow=3)+
  # scale_x_continuous("Dose (uM)",
  #                    trans="log10",
  #                    label = trans_format("log10", math_format(10^.x)))+
  scale_x_continuous("Concentration (uM)",
                     trans="log10",
                     label = trans_format("log10", math_format(10^.x)))+
                     # breaks = c(0,300,600,1200,2400),
                     # label = c(0,300,600,1200,2400))+
  scale_y_continuous("Relative viability",
                     limits=c(0,1.2),
                     breaks = c(0,0.5,1))+
  geom_text(data = label_positions, aes(x = x, y = y, label = label),
  inherit.aes = FALSE, hjust = 0, vjust = 1, fontface = "bold", size = 3.5) +
  cleanup+
  theme(strip.text=element_blank(),
  legend.position = "none",
  axis.text.x=element_text(face="plain",angle=90,hjust=.5,vjust=.5,size = 9),
  axis.text.y=element_text(face = "plain",size=9))+
  # axis.title.x=element_blank(),
  # axis.title.y=element_blank())+
  # scale_fill_manual(values=getPalette(length(unique(data_sum$species))))+
  scale_fill_manual(values=color_values)+
  scale_color_manual(values=color_values)+
  geom_vline(xintercept = .916,linetype="dashed")

ggsave("Figures/Figure_3C/clonalvsdms_mutantstandards.pdf",width=7,height=4,useDingbats=F)

```

