---
title: "replicatecorrelations_figure"
author: "Haider Inam"
date: '2025-08-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))


library(stringr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tictoc)
library(doParallel)
library(foreach)
library(RColorBrewer)
library(ggpubr)
library(pROC)
library(reshape2)
library(dr4pl)
library(tidyr)
library(scales)

cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        # axis.line = element_line(color = "black"),
        axis.text = element_text(face="bold",color="black",size="11"),
        text=element_text(size=11,face="bold"),
        axis.title=element_text(face="bold",size="11"))

```

Data parsing
```{r}
data=read.csv("output/ABLEnrichmentScreens/ABL_Region1234_Tileseq/TileSeq_full_kinase_alldoses_with_lfc_corrected_netgrowths.csv",header = T,stringsAsFactors = F)
# a=data%>%filter(is_intended%in%1,dose%in%"il3")

data=data%>%
  rowwise()%>%
  mutate(netgr_obs_screen1=case_when(ct_screen1_after%in%0.5~-Inf,
                                  T~netgr_obs_screen1),
         netgr_obs_corr_screen1=case_when(ct_screen1_after%in%0.5~-Inf,
                                  T~netgr_obs_corr_screen1),
         netgr_obs_screen2=case_when(ct_screen2_after%in%0.5~-Inf,
                                  T~netgr_obs_screen2),
         netgr_obs_corr_screen2=case_when(ct_screen2_after%in%0.5~-Inf,
                                  T~netgr_obs_corr_screen2))

```

il3
```{r}
data_filtered=data%>%filter(dose%in%"il3",
                   is_intended%in%1)

ggplot(data_filtered%>%filter(!species%in%c("F359C","F359I","M244V"),protein_start>=242,protein_start<=512)%>%arrange(resmuts),aes(x=netgr_obs_corr_screen1,y=netgr_obs_corr_screen2))+
  geom_point(color="black",shape=21,aes(fill=resmuts))+
  # geom_text_repel(aes(label=ifelse(resmuts%in%T,species,"")))+
  geom_abline(linetype="dashed")+
  geom_label_repel(size=2,aes(label=ifelse(resmuts%in%T,species,"")))+
  scale_x_continuous(name="Net Growth Rate Rep A",limits=c(-.015,.08))+
  scale_y_continuous(name="Net Growth Rate Rep B",limits=c(-.015,.08))+
  labs(fill="Sanger\n Mutant")+
  scale_fill_manual(values=c("gray90","red"))+
  stat_cor(method="pearson")+
  coord_equal()+
  cleanup+theme(legend.position = "none")

ggsave("output/replicatecorrelations_figure/3b.baf3_imatinib_correlations_netgr_corrected_DMSO_Tileseq_08032025.pdf",width=4,height=4,units="in",useDingbats=F)

```


300nM
```{r}
data_filtered=data%>%filter(dose%in%"300nM",
                   is_intended%in%1)

ggplot(data_filtered%>%filter(!species%in%c("F359C","F359I","M244V"),protein_start>=242,protein_start<=512)%>%arrange(resmuts),aes(x=netgr_obs_corr_screen1,y=netgr_obs_corr_screen2))+
  geom_point(color="black",shape=21,aes(fill=resmuts))+
  # geom_text_repel(aes(label=ifelse(resmuts%in%T,species,"")))+
  geom_abline(linetype="dashed")+
  geom_label_repel(size=2,aes(label=ifelse(resmuts%in%T,species,"")))+
  scale_x_continuous(name="Net Growth Rate Rep A",limits=c(.03,.055))+
  scale_y_continuous(name="Net Growth Rate Rep B",limits=c(.03,.055))+
  labs(fill="Sanger\n Mutant")+
  scale_fill_manual(values=c("gray90","red"))+
  stat_cor(method="pearson")+
  coord_equal()+
  cleanup+theme(legend.position = "none")

ggsave("output/replicatecorrelations_figure/3b.baf3_imatinib_correlations_netgr_corrected_300nM_Tileseq_08032025.pdf",width=4,height=4,units="in",useDingbats=F)

```


600nM
```{r}
data_filtered=data%>%filter(dose%in%"600nM",
                   is_intended%in%1)

ggplot(data_filtered%>%filter(!species%in%c("F359C","F359I","M244V"),protein_start>=242,protein_start<=512)%>%arrange(resmuts),aes(x=netgr_obs_corr_screen1,y=netgr_obs_corr_screen2))+
  geom_point(color="black",shape=21,aes(fill=resmuts))+
  # geom_text_repel(aes(label=ifelse(resmuts%in%T,species,"")))+
  geom_abline(linetype="dashed")+
  geom_label_repel(size=2,aes(label=ifelse(resmuts%in%T,species,"")))+
  scale_x_continuous(name="Net Growth Rate Rep A",limits=c(-.01,.055))+
  scale_y_continuous(name="Net Growth Rate Rep B",limits=c(-.01,.055))+
  labs(fill="Sanger\n Mutant")+
  scale_fill_manual(values=c("gray90","red"))+
  stat_cor(method="pearson")+
  coord_equal()+
  cleanup+theme(legend.position = "none")

ggsave("output/replicatecorrelations_figure/3b.baf3_imatinib_correlations_netgr_corrected_600nM_Tileseq_08032025.pdf",width=4,height=4,units="in",useDingbats=F)

```

1200nM
```{r}
data_filtered=data%>%filter(dose%in%"1200nM",
                   is_intended%in%1)

ggplot(data_filtered%>%filter(!species%in%c("F359C","F359I","M244V"),protein_start>=242,protein_start<=512)%>%arrange(resmuts),aes(x=netgr_obs_corr_screen1,y=netgr_obs_corr_screen2))+
  geom_point(color="black",shape=21,aes(fill=resmuts))+
  # geom_text_repel(aes(label=ifelse(resmuts%in%T,species,"")))+
  geom_abline(linetype="dashed")+
  geom_label_repel(size=2,aes(label=ifelse(resmuts%in%T,species,"")))+
  scale_x_continuous(name="Net Growth Rate Rep A",limits=c(-.06,.07))+
  scale_y_continuous(name="Net Growth Rate Rep B",limits=c(-.06,.07))+
  labs(fill="Sanger\n Mutant")+
  scale_fill_manual(values=c("gray90","red"))+
  stat_cor(method="pearson")+
  coord_equal()+
  cleanup+theme(legend.position = "none")

ggsave("output/replicatecorrelations_figure/3b.baf3_imatinib_correlations_netgr_corrected_1200nM_Tileseq_08032025.pdf",width=4,height=4,units="in",useDingbats=F)

```

